# Generated by Django 3.1.3 on 2020-11-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50)),
                ('days', models.TextField(default='empty')),
                ('educations', models.TextField(default='empty')),
                ('moreDetail', models.TextField(default='empty')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lessonName', models.CharField(max_length=50)),
                ('vahed', models.PositiveSmallIntegerField()),
                ('collegeName', models.CharField(max_length=50)),
                ('classGender', models.CharField(choices=[('mix', 'mix'), ('male', 'male'), ('female', 'female')], default='mix', max_length=10)),
                ('like', models.IntegerField(default=0)),
                ('unlike', models.IntegerField(default=0)),
                ('mianTermDate', models.DateTimeField()),
                ('termDate', models.DateTimeField()),
                ('teacherName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainApp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='DatesOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekDays', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')], default='شنبه', max_length=50)),
                ('beginTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.lesson')),
            ],
        ),
    ]
