# Generated by Django 3.1.3 on 2020-11-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20201128_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='lessonTeaching',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unlike',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
